name: pure
description: A Social Network Messenger.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  adaptive_dialog: ^1.1.0
  algolia: ^1.0.4
  app_settings: ^4.1.1
  badges: ^2.0.1
  bubble: ^1.2.1
  cupertino_icons: ^1.0.3
  device_info_plus: ^2.2.0
  dio: ^4.0.0
  email_validator: ^2.0.1
  file_picker: ^4.2.3
  flash: ^2.0.1
  flex_color_scheme: ^4.1.1
  float_column: ^1.2.1
  flutter_easyloading: ^3.0.0
  flutter_link_previewer: ^2.6.1
  flutter_linkify: ^5.0.2
  font_awesome_flutter: ^9.2.0
  go_router: ^2.5.2
  intl: ^0.17.0
  linkify: ^4.1.0
  open_file: ^3.2.1
  palette_generator: ^0.3.2
  permission_handler: ^8.3.0
  photo_view: ^0.13.0
  share_plus: ^2.2.0
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  random_color: ^1.0.6-nullsafety
  smooth_page_indicator: ^0.3.0-nullsafety.0
  stream_transform: ^2.0.0
  timeago: ^3.1.0
  url_launcher: ^6.0.17
  uuid: ^3.0.4
  video_player: ^2.2.10
  video_trimmer: ^1.0.0

  # Authentication
  sign_in_with_apple: ^3.3.0
  google_sign_in: ^5.2.1

  # Screen Utilities
  flutter_screenutil: ^5.0.0+2

  # Images
  image_picker: ^0.8.4
  cached_network_image: ^3.1.0
  image_cropper: ^1.4.1
  flutter_image_compress: ^1.1.0

  # State Management
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3

  # Firebase
  cloud_firestore: ^3.1.0
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  firebase_database: ^8.1.0
  firebase_dynamic_links: ^3.0.1
  firebase_messaging: ^11.1.0
  firebase_storage: ^10.1.0
  firebase_crashlytics: ^2.4.4

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true


  assets:
    - assets/images/

  fonts:
    - family: Migra
      fonts:
        - asset: assets/fonts/Migra-Bold.otf
          weight: 800

    - family: PublicSans
      fonts:
        - asset: assets/fonts/PublicSans-Light.otf
          weight: 300
        - asset: assets/fonts/PublicSans-Regular.otf
          weight: 400
        - asset: assets/fonts/PublicSans-Medium.otf
          weight: 500
        - asset: assets/fonts/PublicSans-SemiBold.otf
          weight: 600
        - asset: assets/fonts/PublicSans-Bold.otf
          weight: 700

